//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIQUEJAS.Sql {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sqlLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sqlLogin() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APIQUEJAS.Sql.sqlLogin", typeof(sqlLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Usuario(Usuario, Pass, Nombres, Apellidos, Email, Cui, Departamento, Id_Rol, Id_Cargo, Id_Punto_Atencion, Estado)
        ///VALUES (&apos;{0}&apos;,ENCRYPTBYPASSPHRASE(&apos;JS0R&apos;, &apos;{1}&apos; ),&apos;{2}&apos;,&apos;{3}&apos;,&apos;{4}&apos;,&apos;{5}&apos;,&apos;{6}&apos;,{7},{8},{9},&apos;{10}&apos;);.
        /// </summary>
        internal static string InsertaUsuario {
            get {
                return ResourceManager.GetString("InsertaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT USUARIO.ID_ROL AS ID, ROL.Nombre_Rol AS NOMBRE FROM USUARIO
        ///INNER JOIN ROL	
        ///	ON USUARIO.ID_ROL = ROL.Id_Rol
        ///WHERE USUARIO = &apos;{0}&apos;.
        /// </summary>
        internal static string ObtieneRol {
            get {
                return ResourceManager.GetString("ObtieneRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT COUNT(Id_Usuario) AS EXISTE FROM USUARIO WHERE TRIM(Email) = &apos;{0}&apos; AND Estado = &apos;A&apos;;.
        /// </summary>
        internal static string ValidaCorreoRepetido {
            get {
                return ResourceManager.GetString("ValidaCorreoRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT COUNT(Id_Cuenta) AS EXISTE FROM Cuenta WHERE TRIM(Numero_Cuenta) = &apos;{0}&apos; AND ESTADO = &apos;A&apos;;.
        /// </summary>
        internal static string ValidaCuenta {
            get {
                return ResourceManager.GetString("ValidaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT COUNT(Id_Usuario) AS EXISTE FROM USUARIO WHERE TRIM(Cui) = &apos;{0}&apos; AND Estado = &apos;A&apos;;.
        /// </summary>
        internal static string ValidaCUIRepetido {
            get {
                return ResourceManager.GetString("ValidaCUIRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT COUNT(Id_Usuario) AS EXISTE FROM Usuario WHERE Usuario= &apos;{0}&apos; AND CAST(DECRYPTBYPASSPHRASE(&apos;JS0R&apos;,Pass) AS VARCHAR(MAX)) = &apos;{1}&apos;;.
        /// </summary>
        internal static string ValidaExistenciaUsuario {
            get {
                return ResourceManager.GetString("ValidaExistenciaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT COUNT(Id_Usuario) AS EXISTE FROM Usuario WHERE TRIM(Usuario) = &apos;{0}&apos; AND Estado = &apos;A&apos;;.
        /// </summary>
        internal static string ValidaUsuarioRepetido {
            get {
                return ResourceManager.GetString("ValidaUsuarioRepetido", resourceCulture);
            }
        }
    }
}
