//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIQUEJAS.Sql {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sqlQueja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sqlQueja() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APIQUEJAS.Sql.sqlQueja", typeof(sqlQueja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE Tipo_Queja SET CORRELATIVO = CORRELATIVO + 1 WHERE Id_Tipo = {0}.
        /// </summary>
        internal static string IncrementarCorrelativo {
            get {
                return ResourceManager.GetString("IncrementarCorrelativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO [dbo].[Encabezado_Queja]
        ///           ([Nombres]
        ///           ,[Apellidos]
        ///           ,[Email]
        ///           ,[Telefono]
        ///           ,[Usuario]
        ///           ,[Detalle]
        ///           ,[Id_Estado_Externo]
        ///           ,[Id_Estado_Interno]
        ///           ,[Fecha_Ingreso]
        ///           ,[Id_Tipo]
        ///           ,[Ingreso_Queja]
        ///           ,[Id_Origen]
        ///           ,[Direccion_Archivo]           
        ///           ,[Id_Punto_Atencion]
        ///,[Correlativo])           
        ///     VALUES (&apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;,&apos;{3}&apos;, &apos;{4}&apos;, &apos;{5}&apos;,{6},{ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string InsertaEncabezadoQueja {
            get {
                return ResourceManager.GetString("InsertaEncabezadoQueja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT CORRELATIVO+1 AS Correlativo, Siglas_Tipo FROM Tipo_Queja WHERE ID_TIPO = {0}.
        /// </summary>
        internal static string ObtieneCorrelativoSiguienteQueja {
            get {
                return ResourceManager.GetString("ObtieneCorrelativoSiguienteQueja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select Email from Usuario where Id_Punto_Atencion = 2 AND Id_Cargo = 7 and Estado = &apos;A&apos;.
        /// </summary>
        internal static string ObtieneCorreoCentralizador {
            get {
                return ResourceManager.GetString("ObtieneCorreoCentralizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT Id_Tipo, Siglas_Tipo FROM Tipo_Queja WHERE Estado = &apos;A&apos;.
        /// </summary>
        internal static string ObtieneTiposQueja {
            get {
                return ResourceManager.GetString("ObtieneTiposQueja", resourceCulture);
            }
        }
    }
}
