//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIQUEJAS.Sql {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sqlReporte {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sqlReporte() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APIQUEJAS.Sql.sqlReporte", typeof(sqlReporte).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encabezado_Queja.CORRELATIVO = &apos;{0}&apos;.
        /// </summary>
        internal static string FiltroCorrelativo {
            get {
                return ResourceManager.GetString("FiltroCorrelativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONVERT(varchar(10), Encabezado_Queja.Fecha_Ingreso, 120)  &gt;= &apos;{0}&apos; AND CONVERT(varchar(10), Encabezado_Queja.Fecha_Ingreso, 120) &lt;= &apos;{1}&apos;.
        /// </summary>
        internal static string FiltroFechas {
            get {
                return ResourceManager.GetString("FiltroFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encabezado_Queja.Id_Punto_Atencion = {0}.
        /// </summary>
        internal static string FiltroPuntoAtencion {
            get {
                return ResourceManager.GetString("FiltroPuntoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto_Atencion.Id_Region = {0}.
        /// </summary>
        internal static string FiltroRegion {
            get {
                return ResourceManager.GetString("FiltroRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT Encabezado_Queja.Correlativo, Tipo_Queja.Nombre AS Nombre_Tipo_Queja, Nombre_Punto_Atencion,
        ///ESTADO.Nombre AS Estado_Interno, ESTADO2.Nombre AS Estado_Externo, Encabezado_Queja.JUSTIFICACION, Encabezado_Queja.Detalle,
        ///Origen_Queja.Nombre AS Nombre_Origen, Encabezado_Queja.Fecha_Ingreso
        ///FROM Encabezado_Queja
        ///INNER JOIN Tipo_Queja
        ///	ON Encabezado_Queja.Id_Tipo = Tipo_Queja.Id_Tipo
        ///INNER JOIN Punto_Atencion
        ///	ON Punto_Atencion.Id_Punto_Atencion = Encabezado_Queja.Id_Punto_Atencion
        ///INNER JOIN Estad [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ObtieneQuejasParaReporte {
            get {
                return ResourceManager.GetString("ObtieneQuejasParaReporte", resourceCulture);
            }
        }
    }
}
